version: 2.1

jobs:
  checkout:
    docker:
      - image: ubuntu # Specify the base image for the job
    steps:
      - checkout  # Checkout the code from the repository

  build:
    docker:
      - image: ubuntu # Specify the base image for the job
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Set up Docker Buildx
          command: |
            docker buildx create --use
      - run:
          name: Build and push Docker image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker build -t $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE:$CIRCLE_SHA1 .
            docker push $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE:$CIRCLE_SHA1

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
