version: 2.1

jobs:
  checkout:
    docker:
      - image: ubuntu:20.04  # Specify the base image for the job
    steps:
      - checkout  # Checkout the code from the repository

  build:
    docker:
      - image: docker:20.10  # Use Docker image that already has Docker pre-installed
    steps:
      - checkout
      - run:
          name: Set up Docker Buildx
          command: |
            docker buildx create --use

      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE:$CIRCLE_SHA1 .
            docker push $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE:$CIRCLE_SHA1

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
